// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"
	"github.com/google/wire"
	"github.com/minio/minio-go/v7"
	"github.com/scc749/nimbus-blog-api/config"
	"github.com/scc749/nimbus-blog-api/internal/controller/http"
	"github.com/scc749/nimbus-blog-api/internal/repo"
	"github.com/scc749/nimbus-blog-api/internal/repo/cache"
	"github.com/scc749/nimbus-blog-api/internal/repo/messaging"
	"github.com/scc749/nimbus-blog-api/internal/repo/notification"
	"github.com/scc749/nimbus-blog-api/internal/repo/persistence"
	"github.com/scc749/nimbus-blog-api/internal/repo/storage"
	"github.com/scc749/nimbus-blog-api/internal/repo/viewbuffer"
	"github.com/scc749/nimbus-blog-api/internal/repo/webapi"
	"github.com/scc749/nimbus-blog-api/internal/usecase"
	"github.com/scc749/nimbus-blog-api/internal/usecase/auth"
	"github.com/scc749/nimbus-blog-api/internal/usecase/auth/admin"
	"github.com/scc749/nimbus-blog-api/internal/usecase/auth/user"
	"github.com/scc749/nimbus-blog-api/internal/usecase/captcha"
	"github.com/scc749/nimbus-blog-api/internal/usecase/comment"
	"github.com/scc749/nimbus-blog-api/internal/usecase/content"
	"github.com/scc749/nimbus-blog-api/internal/usecase/email"
	"github.com/scc749/nimbus-blog-api/internal/usecase/feedback"
	"github.com/scc749/nimbus-blog-api/internal/usecase/file"
	"github.com/scc749/nimbus-blog-api/internal/usecase/link"
	notification2 "github.com/scc749/nimbus-blog-api/internal/usecase/notification"
	"github.com/scc749/nimbus-blog-api/internal/usecase/setting"
	user2 "github.com/scc749/nimbus-blog-api/internal/usecase/user"
	"github.com/scc749/nimbus-blog-api/pkg/httpserver"
	"github.com/scc749/nimbus-blog-api/pkg/logger"
	minio2 "github.com/scc749/nimbus-blog-api/pkg/minio"
	"github.com/scc749/nimbus-blog-api/pkg/postgres"
	"github.com/scc749/nimbus-blog-api/pkg/redis"
	"github.com/scc749/nimbus-blog-api/pkg/ssehub"
	"time"
)

// Injectors from wire.go:

// InitializeApp 初始化 App 并返回 cleanup。
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	appInfo := NewAppInfo(cfg)
	loggerInterface := NewLogger(cfg)
	postgres, cleanup, err := NewPostgres(cfg)
	if err != nil {
		return nil, nil, err
	}
	redis, cleanup2, err := NewRedis(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	adminRepo := NewAdminRepo(postgres)
	adminTwoFASetupStore := NewAdminTwoFASetupStore(redis)
	adminAuth := NewAdminAuthUseCase(cfg, adminRepo, adminTwoFASetupStore)
	userRepo := NewUserRepo(postgres)
	tokenSigner, err := NewTokenSigner(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	refreshTokenStore := NewRefreshTokenStore(redis)
	refreshTokenBlacklistRepo := NewRefreshTokenBlacklistRepo(postgres)
	userAuth := NewUserAuthUseCase(userRepo, tokenSigner, refreshTokenStore, refreshTokenBlacklistRepo)
	auth := NewAuthUseCase(adminAuth, userAuth)
	generator := NewCaptchaGenerator(cfg)
	captchaStore := NewCaptchaStore(redis)
	captcha := NewCaptchaUseCase(generator, captchaStore)
	emailSender := NewEmailSender(cfg)
	emailCodeStore := NewEmailCodeStore(redis)
	email := NewEmailUseCase(emailSender, emailCodeStore)
	client, err := NewMinioClient(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	objectStore, err := NewObjectStore(cfg, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fileRepo := NewFileRepo(postgres)
	file := NewFileUseCase(cfg, objectStore, fileRepo)
	user := NewUserUseCase(userRepo)
	translationWebAPI := NewTranslationWebAPI()
	llmWebAPI := NewLLMWebAPI(cfg)
	postRepo := NewPostRepo(postgres)
	tagRepo := NewTagRepo(postgres)
	categoryRepo := NewCategoryRepo(postgres)
	postLikeRepo := NewPostLikeRepo(postgres)
	postViewRepo, cleanup3 := NewPostViewRepo(postgres, loggerInterface)
	content := NewContentUseCase(translationWebAPI, llmWebAPI, adminRepo, postRepo, tagRepo, categoryRepo, postLikeRepo, fileRepo, postViewRepo)
	commentRepo := NewCommentRepo(postgres)
	commentLikeRepo := NewCommentLikeRepo(postgres)
	notificationRepo := NewNotificationRepo(postgres)
	hub := NewSSEHub()
	notifier := NewNotifier(notificationRepo, hub)
	comment := NewCommentUseCase(commentRepo, commentLikeRepo, userRepo, postRepo, notifier)
	feedbackRepo := NewFeedbackRepo(postgres)
	feedback := NewFeedbackUseCase(feedbackRepo)
	linkRepo := NewLinkRepo(postgres)
	link := NewLinkUseCase(linkRepo)
	siteSettingRepo := NewSiteSettingRepo(postgres)
	setting := NewSettingUseCase(siteSettingRepo)
	notification := NewNotificationUseCase(notificationRepo, notifier, hub)
	server := SetupHTTPServer(cfg, loggerInterface, auth, captcha, email, tokenSigner, file, user, content, comment, feedback, link, setting, notification)
	app := NewApp(appInfo, loggerInterface, postgres, redis, server)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Info AppInfo

	Logger     logger.Interface
	Postgres   *postgres.Postgres
	Redis      *redis.Redis
	HTTPServer *httpserver.Server
}

// AppInfo 应用信息。
type AppInfo struct {
	Name    string
	Version string
}

// NewApp 创建 App。
func NewApp(info AppInfo, l logger.Interface, pg *postgres.Postgres, r *redis.Redis, srv *httpserver.Server) *App {
	return &App{
		Info:       info,
		Logger:     l,
		Postgres:   pg,
		Redis:      r,
		HTTPServer: srv,
	}
}

// NewAppInfo 创建 AppInfo。
func NewAppInfo(cfg *config.Config) AppInfo {
	return AppInfo{Name: cfg.App.Name, Version: cfg.App.Version}
}

// NewLogger 创建 Logger。
func NewLogger(cfg *config.Config) logger.Interface {
	return logger.New(cfg.Log.Level)
}

// NewPostgres 创建 Postgres 连接并返回 cleanup。
func NewPostgres(cfg *config.Config) (*postgres.Postgres, func(), error) {
	pg, err := postgres.New(
		cfg.Postgres.Host,
		cfg.Postgres.Port,
		cfg.Postgres.User,
		cfg.Postgres.Password,
		cfg.Postgres.DBName,
		cfg.Postgres.SSLMode,
		cfg.Postgres.TimeZone, postgres.WithMaxIdleConns(cfg.Postgres.MaxIdleConns), postgres.WithMaxOpenConns(cfg.Postgres.MaxOpenConns),
	)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() { pg.Close() }
	return pg, cleanup, nil
}

// NewRedis 创建 Redis 连接并返回 cleanup。
func NewRedis(cfg *config.Config) (*redis.Redis, func(), error) {
	rdb, err := redis.New(cfg.Redis.Host, cfg.Redis.Port, cfg.Redis.Password, cfg.Redis.DB)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() { rdb.Close() }
	return rdb, cleanup, nil
}

// NewMinioClient 创建 MinIO Client 并确保默认 bucket 存在。
func NewMinioClient(cfg *config.Config) (*minio.Client, error) {
	cli, err := minio2.New(
		cfg.MinIO.Endpoint,
		cfg.MinIO.AccessKey,
		cfg.MinIO.SecretKey,
		cfg.MinIO.UseSSL, minio2.WithDefaultBucket(cfg.MinIO.Bucket), minio2.WithRegion(cfg.MinIO.Region),
	)
	if err != nil {
		return nil, err
	}
	if cfg.MinIO.Bucket != "" {
		_ = cli.EnsureBucket(context.Background(), cfg.MinIO.Bucket)
	}
	return cli.CLI, nil
}

func NewAdminRepo(pg *postgres.Postgres) repo.AdminRepo {
	return persistence.NewAdminRepo(pg.DB)
}

func NewUserRepo(pg *postgres.Postgres) repo.UserRepo {
	return persistence.NewUserRepo(pg.DB)
}

func NewPostRepo(pg *postgres.Postgres) repo.PostRepo {
	return persistence.NewPostRepo(pg.DB)
}

func NewTagRepo(pg *postgres.Postgres) repo.TagRepo {
	return persistence.NewTagRepo(pg.DB)
}

func NewCategoryRepo(pg *postgres.Postgres) repo.CategoryRepo {
	return persistence.NewCategoryRepo(pg.DB)
}

func NewCommentRepo(pg *postgres.Postgres) repo.CommentRepo {
	return persistence.NewCommentRepo(pg.DB)
}

func NewPostLikeRepo(pg *postgres.Postgres) repo.PostLikeRepo {
	return persistence.NewPostLikeRepo(pg.DB)
}

func NewCommentLikeRepo(pg *postgres.Postgres) repo.CommentLikeRepo {
	return persistence.NewCommentLikeRepo(pg.DB)
}

func NewFeedbackRepo(pg *postgres.Postgres) repo.FeedbackRepo {
	return persistence.NewFeedbackRepo(pg.DB)
}

func NewLinkRepo(pg *postgres.Postgres) repo.LinkRepo {
	return persistence.NewLinkRepo(pg.DB)
}

func NewSiteSettingRepo(pg *postgres.Postgres) repo.SiteSettingRepo {
	return persistence.NewSiteSettingRepo(pg.DB)
}

func NewFileRepo(pg *postgres.Postgres) repo.FileRepo {
	return persistence.NewFileRepo(pg.DB)
}

func NewNotificationRepo(pg *postgres.Postgres) repo.NotificationRepo {
	return persistence.NewNotificationRepo(pg.DB)
}

func NewRefreshTokenBlacklistRepo(pg *postgres.Postgres) repo.RefreshTokenBlacklistRepo {
	return persistence.NewRefreshTokenBlacklistPostgres(pg.DB)
}

func NewPostViewRepo(pg *postgres.Postgres, l logger.Interface) (repo.PostViewRepo, func()) {
	return viewbuffer.New(pg.DB, l)
}

func NewCaptchaStore(r *redis.Redis) repo.CaptchaStore {
	return cache.NewCaptchaRedisStore(r, 5*time.Minute)
}

func NewEmailCodeStore(r *redis.Redis) repo.EmailCodeStore {
	return cache.NewEmailCodeRedisStore(r, 10*time.Minute)
}

func NewRefreshTokenStore(r *redis.Redis) repo.RefreshTokenStore {
	return cache.NewRefreshTokenRedisStore(r)
}

func NewAdminTwoFASetupStore(r *redis.Redis) repo.AdminTwoFASetupStore {
	return cache.NewAdminTwoFARedisStore(r)
}

func NewObjectStore(cfg *config.Config, cli *minio.Client) (repo.ObjectStore, error) {
	provider := cfg.File.Provider
	if provider == "" || provider == "minio" {
		return storage.NewMinioStore(cli, cfg.File.PublicBaseURL), nil
	}
	return nil, fmt.Errorf("unsupported file storage provider: %s", provider)
}

func NewEmailSender(cfg *config.Config) repo.EmailSender {
	return messaging.NewSMTPEmailSender(
		cfg.SMTP.Host,
		cfg.SMTP.Port,
		cfg.SMTP.Username,
		cfg.SMTP.Password,
		cfg.SMTP.From,
	)
}

func NewTranslationWebAPI() repo.TranslationWebAPI {
	return webapi.NewTranslationWebAPI()
}

func NewLLMWebAPI(cfg *config.Config) repo.LLMWebAPI {
	return webapi.NewLLMWebAPI(cfg.OpenAI.APIKey, cfg.OpenAI.BaseURL, cfg.OpenAI.Model)
}

func NewTokenSigner(cfg *config.Config) (user.TokenSigner, error) {
	return user.NewTokenSigner(
		cfg.JWT.AccessSecret,
		cfg.JWT.RefreshSecret,
		cfg.JWT.AccessTTL,
		cfg.JWT.RefreshTTL,
		cfg.JWT.Issuer,
	)
}

func NewAdminAuthUseCase(cfg *config.Config, adminRepo repo.AdminRepo, twoFASetupStore repo.AdminTwoFASetupStore) usecase.AdminAuth {
	totpCfg := admin.TOTPConfig{QRWidth: cfg.TwoFA.QRWidth, QRHeight: cfg.TwoFA.QRHeight}
	enc := admin.NewEncryptorFromSecret(cfg.TwoFA.EncryptionKey)
	return admin.New(adminRepo, twoFASetupStore, cfg.App.Name, admin.NewTOTPProviderWithConfig(totpCfg), enc)
}

func NewUserAuthUseCase(userRepo repo.UserRepo, signer user.TokenSigner, refreshStore repo.RefreshTokenStore, refreshBlacklist repo.RefreshTokenBlacklistRepo) usecase.UserAuth {
	return user.New(userRepo, signer, refreshStore, refreshBlacklist)
}

func NewAuthUseCase(adminAuth usecase.AdminAuth, userAuth usecase.UserAuth) usecase.Auth {
	return auth.New(adminAuth, userAuth)
}

func NewCaptchaGenerator(cfg *config.Config) captcha.Generator {
	return captcha.NewBase64Generator(captcha.Config{
		Height:   cfg.Captcha.Height,
		Width:    cfg.Captcha.Width,
		Length:   cfg.Captcha.Length,
		MaxSkew:  cfg.Captcha.MaxSkew,
		DotCount: cfg.Captcha.DotCount,
	})
}

func NewCaptchaUseCase(gen captcha.Generator, store repo.CaptchaStore) usecase.Captcha {
	return captcha.New(store, gen)
}

func NewEmailUseCase(sender repo.EmailSender, codeStore repo.EmailCodeStore) usecase.Email {
	return email.New(sender, codeStore)
}

func NewFileUseCase(cfg *config.Config, objectStore repo.ObjectStore, fileRepo repo.FileRepo) usecase.File {
	return file.New(objectStore, fileRepo, cfg.MinIO.Bucket)
}

func NewUserUseCase(userRepo repo.UserRepo) usecase.User {
	return user2.New(userRepo)
}

func NewContentUseCase(translationAPI repo.TranslationWebAPI, llmAPI repo.LLMWebAPI, adminRepo repo.AdminRepo, postRepo repo.PostRepo, tagRepo repo.TagRepo, categoryRepo repo.CategoryRepo, postLikeRepo repo.PostLikeRepo, fileRepo repo.FileRepo, postViewRepo repo.PostViewRepo) usecase.Content {
	return content.New(translationAPI, llmAPI, adminRepo, postRepo, tagRepo, categoryRepo, postLikeRepo, fileRepo, postViewRepo, content.NewCalculator())
}

func NewCommentUseCase(commentRepo repo.CommentRepo, commentLikeRepo repo.CommentLikeRepo, userRepo repo.UserRepo, postRepo repo.PostRepo, notifier repo.Notifier) usecase.Comment {
	return comment.New(commentRepo, commentLikeRepo, userRepo, postRepo, notifier)
}

func NewFeedbackUseCase(feedbackRepo repo.FeedbackRepo) usecase.Feedback {
	return feedback.New(feedbackRepo)
}

func NewLinkUseCase(linkRepo repo.LinkRepo) usecase.Link {
	return link.New(linkRepo)
}

func NewSettingUseCase(settingRepo repo.SiteSettingRepo) usecase.Setting {
	return setting.New(settingRepo)
}

func NewSSEHub() *ssehub.Hub {
	return ssehub.New()
}

func NewNotifier(notificationRepo repo.NotificationRepo, hub *ssehub.Hub) repo.Notifier {
	return notification.NewNotifier(notificationRepo, hub)
}

func NewNotificationUseCase(notificationRepo repo.NotificationRepo, notifier repo.Notifier, hub *ssehub.Hub) usecase.Notification {
	return notification2.New(notificationRepo, notifier, hub)
}

func SetupHTTPServer(
	cfg *config.Config, l logger.Interface, auth2 usecase.Auth,
	captchaUC usecase.Captcha, emailUC usecase.Email, signer user.TokenSigner,
	fileUC usecase.File, userUC usecase.User, contentUC usecase.Content, commentUC usecase.Comment,
	feedbackUC usecase.Feedback, linkUC usecase.Link, settingUC usecase.Setting,
	notificationUC usecase.Notification,
) *httpserver.Server {
	srv := httpserver.New(l, httpserver.WithPort(cfg.HTTP.Port), httpserver.WithPrefork(cfg.HTTP.UsePreforkMode))
	http.NewRouter(srv.App, cfg, l, auth2, captchaUC, emailUC, signer, fileUC, userUC, contentUC, commentUC, feedbackUC, linkUC, settingUC, notificationUC)
	return srv
}

// ProviderSet Wire ProviderSet。
var ProviderSet = wire.NewSet(

	NewAppInfo,
	NewLogger,
	NewApp,

	NewPostgres,
	NewRedis,
	NewMinioClient,

	NewAdminRepo,
	NewUserRepo,
	NewPostRepo,
	NewTagRepo,
	NewCategoryRepo,
	NewCommentRepo,
	NewPostLikeRepo,
	NewCommentLikeRepo,
	NewFeedbackRepo,
	NewLinkRepo,
	NewSiteSettingRepo,
	NewFileRepo,
	NewNotificationRepo,
	NewRefreshTokenBlacklistRepo,

	NewPostViewRepo,

	NewCaptchaStore,
	NewEmailCodeStore,
	NewRefreshTokenStore,
	NewAdminTwoFASetupStore,

	NewObjectStore,

	NewEmailSender,

	NewTranslationWebAPI,
	NewLLMWebAPI,

	NewTokenSigner,
	NewAdminAuthUseCase,
	NewUserAuthUseCase,
	NewAuthUseCase,

	NewCaptchaGenerator,
	NewCaptchaUseCase,

	NewEmailUseCase,

	NewFileUseCase,

	NewUserUseCase,

	NewContentUseCase,

	NewCommentUseCase,

	NewFeedbackUseCase,

	NewLinkUseCase,

	NewSettingUseCase,

	NewSSEHub,

	NewNotifier,

	NewNotificationUseCase,

	SetupHTTPServer,
)
